apiVersion: v1
kind: ReplicationController
metadata:
  name: portal
  labels:
    name: portal
spec:
  replicas: 1
  selector:
    name: portal
  template:
    metadata:
      labels:
        name: portal
    spec:
      containers:
      - name: portal
        image: my/portal
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    name: portal
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector: 
    name: portal
