apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoringserver
  labels:
    name: monitoringserver
spec:
  replicas: 1
  selector:
    name: monitoringserver
  template:
    metadata:
      labels:
        name: monitoringserver
    spec:
      containers:
      - name: monitoringserver
        image: my/monitoringserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: monitoringserver
  labels:
    name: monitoringserver
spec:
  type: NodePort
  ports:
  - port: 22
    name: ssh
  selector: 
    name: monitoringserver
