apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoringserver
  labels:
    name: monitoringserver
spec:
  replicas: 1
  selector:
    name: monitoringserver
  template:
    metadata:
      labels:
        name: monitoringserver
    spec:
      containers:
      - name: monitoringserver
        image: my/monitoringserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
