apiVersion: v1
kind: Service
metadata:
  name: monitoringserver
  labels:
    name: monitoringserver
spec:
  type: NodePort
  ports:
  - port: 22
    name: ssh
  selector: 
    name: monitoringserver
