<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="anotherMicroserviceMetamodel" nsURI="http://www.example.org/anotherMicroserviceMetamodel"
    nsPrefix="anotherMicroserviceMetamodel">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore.xml.type" value="http://www.eclipse.org/emf/2003/XMLType"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Microservice">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="typeAndVersionMatch"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="typeAndVersionMatch" value="microserviceType.versions->select(v:Version | v = version)->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        eType="#//ExecutionEnvironment" eOpposite="#//ExecutionEnvironment/microservices"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoints" lowerBound="1"
        upperBound="-1" eType="#//Endpoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="microserviceType" lowerBound="1"
        eType="#//MicroserviceType" eOpposite="#//MicroserviceType/microservices"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" lowerBound="1"
        eType="#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="microservices" lowerBound="1"
        upperBound="-1" eType="#//Microservice" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionEnvironment" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="microservices" upperBound="-1"
        eType="#//Microservice" eOpposite="#//Microservice/environment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Version">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionString" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RESTVerb">
    <eLiterals name="GET"/>
    <eLiterals name="PUT" value="1"/>
    <eLiterals name="POST" value="2"/>
    <eLiterals name="DELETE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Endpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="restOperations" lowerBound="1"
        upperBound="-1" eType="#//RESTOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ipAddress" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IntObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RESTOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restVerb" lowerBound="1"
        eType="#//RESTVerb"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MicroserviceType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="restOperations" upperBound="-1"
        eType="#//RESTOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="microservices" upperBound="-1"
        eType="#//Microservice" eOpposite="#//Microservice/microserviceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versions" lowerBound="1"
        upperBound="-1" eType="#//Version" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//OperationToOperationCallingDependency" eOpposite="#//OperationToOperationCallingDependency/callingMicroservice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MicroserviceRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="microserviceTypes" lowerBound="1"
        upperBound="-1" eType="#//MicroserviceType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Host" abstract="true" eSuperTypes="#//ExecutionEnvironment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//Container" containment="true" eOpposite="#//Container/host"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container" abstract="true" eSuperTypes="#//ExecutionEnvironment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="host" lowerBound="1" eType="#//Host"
        eOpposite="#//Host/containers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualHost" eSuperTypes="#//Host">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentHost" lowerBound="1"
        eType="#//PhysicalHost" eOpposite="#//PhysicalHost/virtualHosts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalHost" eSuperTypes="#//Host">
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualHosts" upperBound="-1"
        eType="#//VirtualHost" containment="true" eOpposite="#//VirtualHost/parentHost"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfrastructureModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hosts" lowerBound="1" upperBound="-1"
        eType="#//PhysicalHost" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationToOperationCallingDependencies"
        upperBound="-1" eType="#//OperationToOperationCallingDependency" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationToOperationCallingDependency">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="calledCorrespond callingCorrespond callingVersionFits"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="calledCorrespond" value="calledMicroservice.restOperations->select(rop:RESTOperation | rop=calledOperation)->notEmpty()"/>
      <details key="callingCorrespond" value="callingMicroservice.restOperations->select(rop:RESTOperation | rop=callingOperation)->notEmpty()"/>
      <details key="callingVersionFits" value="callingMicroservice.versions->select(ver:Version|ver=callingVersion)->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calledMicroservice" lowerBound="1"
        eType="#//MicroserviceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calledOperation" lowerBound="1"
        eType="#//RESTOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callingOperation" lowerBound="1"
        eType="#//RESTOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callingVersion" lowerBound="1"
        eType="#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callingMicroservice" lowerBound="1"
        eType="#//MicroserviceType" eOpposite="#//MicroserviceType/dependencies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeSeries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeSeriesPoints" upperBound="-1"
        eType="#//TimeSeriesPoint" containment="true" eOpposite="#//TimeSeriesPoint/timeSeries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeSeriesPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeSeries" lowerBound="1"
        eType="#//TimeSeries" eOpposite="#//TimeSeries/timeSeriesPoints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MicroserviceOperationTimeSeriesPoint"
      eSuperTypes="#//TimeSeriesPoint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nonNullReferences correspondingReferences"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nonNullReferences" value="endpoint &lt;> null and restOperation &lt;> null"/>
      <details key="correspondingReferences" value="endpoint.restOperations->select(rop:RESTOperation | rop = restOperation)->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoint" lowerBound="1"
        eType="#//Endpoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="restOperation" lowerBound="1"
        eType="#//RESTOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaModelStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="infrastructure" lowerBound="1"
        eType="#//InfrastructureModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" lowerBound="1"
        upperBound="-1" eType="#//Configuration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" lowerBound="1"
        eType="#//DependencyModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeSeries" lowerBound="1"
        eType="#//TimeSeries" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="microserviceRepository"
        lowerBound="1" eType="#//MicroserviceRepository" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
