apiVersion: v1
kind: ReplicationController
metadata:
  name: logic
  labels:
    name: logic
spec:
  replicas: 1
  selector:
    name: logic
  template:
    metadata:
      labels:
        name: logic
    spec:
      containers:
      - name: logic
        image: my/container:logic
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: logic
  labels:
    name: logic
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector: 
    name: logic
