apiVersion: v1
kind: ReplicationController
metadata:
  name: database
  labels:
    name: database
spec:
  replicas: 1
  selector:
    name: database
  template:
    metadata:
      labels:
        name: database
    spec:
      containers:
      - name: database
        image: my/database
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
