apiVersion: v1
kind: ReplicationController
metadata:
  name: logic
  labels:
    name: logic
spec:
  replicas: 1
  selector:
    name: logic
  template:
    metadata:
      labels:
        name: logic
    spec:
      containers:
      - name: logic
        image: my/logic
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
